services:
  elasticsearch:
    image: elasticsearch:9.1.4
    container_name: elasticsearch
    restart: always
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enabled=false  # Disable security for local development
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - elk-network

  logstash:
    image: logstash:9.1.4
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '5044:5044'
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - elk-network

  kibana:
    image: kibana:9.1.4
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=53cret
      - MYSQL_DATABASE=customer-service-db
      - MYSQL_USER=yu71
      - MYSQL_PASSWORD=53cret
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge

volumes:
  elastic_data: { }
  mysql_data: { }